services:
  # База данных сервиса авторизации
  postgres:
    container_name: postgres_go
    image: postgres:16.4
    environment:
      - 'POSTGRES_USER=${DB_USER}'
      - 'POSTGRES_PASSWORD=${DB_PASSWORD}'
      - 'POSTGRES_DB=${DB_NAME}'
    volumes:
      - postgres_data:/var/lib/postgresql/data # Host-mounted volume
    ports:
      # - '${DB_PORT}:5432'
      - '5432:5432'
    networks:
      - app-network # Добавлено подключение к сети

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
