hh:
  enabled: true # разрешено ли использовать этот конфиг
  base_url: 'https://api.hh.ru/vacancies' #базовый URL для формирования поиска по запросу
  health_endpoint: 'https://api.hh.ru/vacancies?per_page=1' # проверка что API сервиса - в рабочем состоянии
  api_key: 'your_hh_api_key_here' # если нужен
  timeout: 30s # общий таймаут для клиента, Значение достаточно большое, но ограничивающее "вечные" запросы
  rate_limit: 2s # для HH.ru есть ограничение не более 30 запросов/мин, значит интервал между запросами = 2с
  max_concurrent: 10 # меньше concurrent запросов
  circuit_breaker:
    failure_threshold: 5 # порог количества неудачных запросов, после которого сработает citrut breaker
    success_threshold: 3 # Кол-во успешных запросов для перехода в Closed
    half_open_max_requests: 2 # максимальное кол-во запросов в Half-Open состоянии, чтобы перейти в состояние Closed
    reset_timeout: 10s # оффсет, после котрого переходим в сотояние Closed
    window_duration: 10s
  max_idle_conns: 10 # максимальное количество бездействующих (keep-alive) соединений для http клиента (экономия ресурсов)
  idle_conn_timeout: 90s # интервал, через сколько закрывать неиспользуемое соединение
  tls_handshake_timeout: 10s # максимальное время ожидания завершения TLS handshake
  response_header_timeout: 5s # интервал, сколько ждать ответа сервера после отправки запроса
  expect_continue_timeout: 1s # интервал, оптимизация для сценариев загрузки больших данных

superjob:
  enabled: true # разрешено ли использовать этот конфиг
  base_url: 'https://api.superjob.ru/2.0/vacancies/' #базовый URL для формирования поиска по запросу
  health_endpoint: 'https://api.superjob.ru/2.0/vacancies/?count=1' # проверка что API сервиса - в рабочем состоянии
  api_key: 'v3.r.137656321.7a5d9a8f8a6b...' # ваш ключ SuperJob
  timeout: 30s # общий таймаут для клиента, Значение достаточно большое, но ограничивающее "вечные" запросы
  rate_limit: 1s # другой rate limit для SuperJob
  max_concurrent: 5 # меньше concurrent запросов
  circuit_breaker:
    failure_threshold: 3 # порог количества неудачных запросов, после которого сработает citrut breaker
    success_threshold: 2 # Кол-во успешных запросов для перехода в Closed
    half_open_max_requests: 1 # максимальное кол-во запросов в Half-Open состоянии, чтобы перейти в состояние Closed
    reset_timeout: 15s # оффсет, после котрого переходим в сотояние Closed
    window_duration: 15s
  max_idle_conns: 5 # максимальное количество бездействующих (keep-alive) соединений для http клиента (экономия ресурсов)
  idle_conn_timeout: 90s # интервал, через сколько закрывать неиспользуемое соединение
  tls_handshake_timeout: 10s # максимальное время ожидания завершения TLS handshake
  response_header_timeout: 5s # интервал, сколько ждать ответа сервера после отправки запроса
  expect_continue_timeout: 1s # интервал, оптимизация для сценариев загрузки больших данных
