dsn: 'host=localhost user=AnumSmart password=admin_26 dbname=users port=5432 sslmode=disable'
max_conns: 10
min_conns: 2
health_check_period: 1m
max_conn_lifetime: 1h
max_conn_idle_time: 30m
connect_timeout: 5s
